anfema/website

app/styles/components/_projects-list.scss
contents/de/projects/5.mystaffpilot.yaml
contents/en/projects/5.mystaffpilot.yaml

BUGFIX: Hide MYSTAFFPILOT from projects list

---

app/styles/components/_project-triptych.scss

BUGFIX: Add shadows to triptych images

---

app/styles/components/_content-quote.scss
app/styles/components/_project-cover.scss
app/styles/components/_project-text.scss
app/ui/components/project-text/component.js
contents/de/projects/1.bmw7series.yaml
contents/de/projects/2.knauf.yaml
contents/de/projects/3.idnow.yaml
contents/de/projects/4.takeda.yaml
contents/de/projects/5.mystaffpilot.yaml
contents/de/projects/6.tods.yaml
contents/de/projects/7.pingonaut.yaml
contents/de/projects/8.ferchau.yaml
contents/en/projects/1.bmw7series.yaml
contents/en/projects/2.knauf.yaml
contents/en/projects/3.idnow.yaml
contents/en/projects/4.takeda.yaml
contents/en/projects/5.mystaffpilot.yaml
contents/en/projects/6.tods.yaml
contents/en/projects/7.pingonaut.yaml
contents/en/projects/8.ferchau.yaml

Provide whitespaces in project detail pages as defined in designs
Re #222

BUGFIX: Provide expected whitespaces

---

app/ui/application/route.js
tests/acceptance/index-test.js
tests/unit/ui/application/route-test.js

Redirect to english or german version depending on user-client-language settings
Re: #243

FEATURE: Automatically redirect non German speaking users to the English version

---

app/styles/_environment/_typography.scss
app/styles/components/_content-lp-text.scss

FEATURE: limit width and align text blocks for content-lp-text component

---

app/styles/_config/__variables.scss
contents/de/index.yaml
contents/en/index.yaml

FEATURE: style links and hide job advertisement-items until job offers are handled

---

app/styles/components/_content-lp-team.scss
contents/en/index.yaml

add missing pagination attributes for content-lp-team component to english translation file to fix rendering problems with this component
Re: #258

BUGFIX: add missing pagination attributes for content-lp-team component

---

.eslintrc.js
app/styles/components/_content-quote.scss

FEATURE: style content-quote component for large screens

---

.gitignore
app/styles/components/_project-triptych.scss

BUGFIX: Fix layout issues with triptych for FF

---

.gitignore
app/styles/components/_content-lp-text.scss
app/styles/components/_content-quote.scss

add vertical spacing to content-lp-text change alignment of content-quote according to screendesign
Re: #263

BUGFIX: add vertical spacing to content-lp-text

---

app/styles/components/_content-lp-team.scss

BUGFIX: Reduced top spacing of content-lp-team component

---

contents/de/projects/2.knauf.yaml
contents/en/projects/1.bmw7series.yaml
contents/en/projects/2.knauf.yaml
contents/en/projects/3.idnow.yaml
contents/en/projects/6.tods.yaml
contents/en/projects/7.pingonaut.yaml
contents/en/projects/8.ferchau.yaml

BUGFIX: change image paths in english translation files

---

app/styles/_config/_functions/_inline-svg.scss
app/styles/_config/_mixins/_webfonts.scss
app/styles/components/_project-gallery.scss
app/styles/components/_project-triptych.scss
app/ui/application/route.js

BUGFIX: get accept-language from fastboot headers

---

app/ui/components/content-project-video/template.hbs
contents/de/projects/1.bmw7series.yaml
contents/de/projects/2.knauf.yaml
contents/en/projects/1.bmw7series.yaml
contents/en/projects/2.knauf.yaml
tests/integration/ui/components/content-project-video/component-test.js

BUGFIX: change video paths to match new directory structure

---

app/ui/components/content-slider/template.hbs

BUGFIX: add alt-text to arrow left and right images

---

app/services/head-data.js
app/styles/_config/__variables.scss
app/styles/components/_page-menu.scss
app/styles/components/_page-overlay.scss
app/ui/components/page-menu/component.js
app/ui/components/page-overlay/template.hbs
app/ui/components/project-detail/component.js
app/ui/components/projects-list-item/component.js
tests/integration/ui/components/projects-list-item/component-test.js
tests/unit/services/head-data-test.js

FEATURE: Remove borders form navigation and project view

---

.travis.yml

Fix travis deploy config

---

contents/de/index.yaml
contents/en/index.yaml

add new vacancys and remove old one

---

app/styles/components/_project-text.scss
app/ui/components/project-text/template.hbs
contents/de/projects/5.mystaffpilot.yaml

Enhancement: Add assets for msp
Re #375

Enhancement: Add assets for msp

---

app/styles/components/_project-icons.scss
app/ui/components/project-icons/template.hbs
app/ui/components/project-text/template.hbs
contents/de/projects/5.mystaffpilot.yaml

Enhancement: Fix project-icons component
Re #381

Enhancement: Fix project-icons component

---

app/styles/_config/_mixins/_offsets.scss
app/styles/components/_project-header.scss

Enhancement: Fix spacing on mobile
Re #380

Enhancement: Fix spacing on mobile

---

app/styles/_config/_mixins/_customers.scss
app/styles/components/_project-header.scss
app/ui/components/project-header/template.hbs
contents/de/projects/5.mystaffpilot.yaml

Enhancement: Update style of project header
Re #384

Enhancement: Update style of project header

---

app/styles/components/_contact.scss
app/ui/components/contact/component.js
app/ui/components/contact/template.hbs
app/ui/components/page-footer/template.hbs
contents/de/projects/5.mystaffpilot.yaml

Bug: Fix mailto-link in page-footer component 
Re #385

Bug: Fix mailto-link in page-footer component

---

app/styles/components/_content-quote.scss

Enhancement: Fix styling of content-quote
Re #396

Enhancement: Fix styling of content-quote

---

.eslintrc.js
package.json
yarn.lock

downgrade eslint until anfema-ruleset is updated

---

contents/en/projects/5.mystaffpilot.yaml

Bug: Check project for missing translations
Re #400

Bug: Check project for missing translations

---

app/app.js
app/router.js
app/ui/components/contact/component.js
app/ui/language/index/controller.js
config/environment.js
tests/integration/ui/components/contact/component-test.js
yarn.lock

fix lint-errors due to ember updates

---

app/styles/_global.scss

Enhancement: Refactor styling of body instead of using .ember-view class
Re #388

Enhancement: Refactor styling of body instead of using .ember-view class

---

app/styles/_config/_mixins/_customers.scss
contents/de/projects/3.idnow.yaml
contents/en/projects/3.idnow.yaml

Enhancement: Update IDnow project-detail page
Re #407

Enhancement: Update IDnow project-detail page

---

app/styles/_config/_mixins/_customers.scss
contents/de/projects/6.tods.yaml
contents/en/projects/6.tods.yaml

Enhancement: Update Tod's project-detail page
Re #408

Enhancement: Update Tod's project-detail page

---

app/styles/_config/_mixins/_customers.scss
app/ui/components/project-icons/template.hbs
contents/de/projects/7.pingonaut.yaml
contents/en/projects/7.pingonaut.yaml

Enhancement: Update Pingonaut project-detail page
Re #409

Enhancement: Update Pingonaut project-detail page

---

app/styles/_config/_mixins/_customers.scss
contents/de/projects/8.ferchau.yaml
contents/en/projects/8.ferchau.yaml

Enhancement: Update Ferchau project-detail page
Re #410

Enhancement: Update Ferchau project-detail page

---

app/styles/_config/_mixins/_customers.scss
app/styles/components/_project-icons.scss
contents/de/projects/9.audi.yaml
contents/en/projects/9.audi.yaml

Enhancement: Create Audi project-detail page
Re #399

Enhancement: Create Audi project-detail page

---

app/styles/components/_project-header.scss
app/styles/components/_project-icons.scss
app/ui/components/project-icons/template.hbs
contents/de/projects/10.paulaner.yaml
contents/de/projects/5.mystaffpilot.yaml
contents/de/projects/9.audi.yaml
contents/en/projects/10.paulaner.yaml
contents/en/projects/5.mystaffpilot.yaml
contents/en/projects/9.audi.yaml

Enhancement: Add english translation for Audi
Re #423

Enhancement: Add english translation for Audi

---

contents/en/projects/10.paulaner.yaml

Enhancement: Add english translation for Paulaner
Re #424

Enhancement: Add english translation for Paulaner

---

app/styles/components/_content-lp-cover.scss
app/styles/components/_content-lp-text.scss
app/styles/components/_services-slide.scss

Enhancement: Fix text styling of landingpage
Re #425

Enhancement: Fix text styling of landingpage

---

app/styles/components/_content-lp-cover.scss
app/styles/components/_project-header.scss

Enhancement: Add cursor: pointer to project-header__scroll-down
Re #432

Enhancement: Add cursor: pointer to project-header__scroll-down

---

app/styles/components/_content-lp-cover.scss
app/styles/components/_project-header.scss

Enhancement: Add header animations
Re #429

Enhancement: Add header animations

---

app/styles/_config/_mixins/_customers.scss
app/styles/components/_page-overlay.scss
app/styles/components/_projects-list.scss
app/ui/components/projects-list-item/template.hbs
contents/de/projects/1.bmw.yaml
contents/de/projects/10.paulaner.yaml
contents/de/projects/2.knauf.yaml
contents/de/projects/3.idnow.yaml
contents/de/projects/5.mystaffpilot.yaml
contents/de/projects/6.tods.yaml
contents/de/projects/7.pingonaut.yaml
contents/de/projects/8.ferchau.yaml
contents/de/projects/9.audi.yaml
contents/en/projects/1.bmw.yaml
contents/en/projects/10.paulaner.yaml
contents/en/projects/2.knauf.yaml
contents/en/projects/3.idnow.yaml
contents/en/projects/5.mystaffpilot.yaml
contents/en/projects/6.tods.yaml
contents/en/projects/7.pingonaut.yaml
contents/en/projects/8.ferchau.yaml
contents/en/projects/9.audi.yaml
tests/integration/ui/components/job-advertisements-item/component-test.js
tests/integration/ui/components/project-cover/component-test.js
tests/integration/ui/components/projects-list-item/component-test.js
tests/integration/ui/components/projects-list/component-test.js

Enhancement: Update style of project overview
Re #436

Enhancement: Update style of project overview

---

contents/de/projects/1.bmw.yaml
contents/de/projects/10.paulaner.yaml
contents/de/projects/2.knauf.yaml
contents/de/projects/3.idnow.yaml
contents/de/projects/5.mystaffpilot.yaml
contents/de/projects/6.tods.yaml
contents/de/projects/7.pingonaut.yaml
contents/de/projects/8.ferchau.yaml
contents/de/projects/9.audi.yaml
contents/en/projects/1.bmw.yaml
contents/en/projects/10.paulaner.yaml
contents/en/projects/2.knauf.yaml
contents/en/projects/3.idnow.yaml
contents/en/projects/5.mystaffpilot.yaml
contents/en/projects/6.tods.yaml
contents/en/projects/7.pingonaut.yaml
contents/en/projects/8.ferchau.yaml
contents/en/projects/9.audi.yaml

Enhancement: Update translations
Re #431

Enhancement: Update translations

---

app/styles/_config/_mixins/_offsets.scss
app/styles/components/_content-quote.scss
app/styles/components/_project-features.scss
app/styles/components/_project-icons.scss
app/styles/components/_project-text.scss
app/ui/components/content-quote/template.hbs
app/ui/components/project-text/template.hbs

Enhancement: Improve responsive behavior
Re #445

Enhancement: Improve responsive behavior

---

app/styles/components/_content-quote.scss
app/styles/components/_project-features.scss
app/styles/components/_project-icons.scss
app/styles/components/_project-text.scss
app/ui/components/content-quote/template.hbs
app/ui/components/project-text/template.hbs

Enhancement: Add container to project pages
Re #440

Enhancement: Add container to project pages

---

app/helpers/equal.js
app/styles/components/_content-lp-team.scss
app/ui/components/content-lp-team-item/component.js
app/ui/components/content-lp-team-item/template.hbs
app/ui/components/content-lp-team/component.js
app/ui/components/content-lp-team/template.hbs
tests/integration/helpers/equal-test.js
tests/integration/ui/components/content-lp-team-item/component-test.js

pass arguments to identify active item and collapse it after switching to the next one
Re #437

Fix event listener on team component

---

app/styles/components/_project-header.scss

Enhancement: Update section-images
Re #441

Enhancement: Update section-images

---

app/styles/components/_contact.scss

Enhancement: Fix style of contact component
Re #452

Enhancement: Fix style of contact component

---

app/styles/components/_content-quote.scss
app/styles/components/_project-text.scss
contents/de/projects/10.paulaner.yaml

Enhancement: Small style fixes
Re #454

Enhancement: Small style fixes

---

app/ui/projects/detail/template.hbs

Enhancement: Fix breadcrumbs
Re #455

Enhancement: Fix breadcrumbs

---

app/styles/components/_content-quote.scss
app/ui/components/content-quote/template.hbs
contents/de/projects/5.mystaffpilot.yaml
contents/en/projects/5.mystaffpilot.yaml
tests/unit/ui/projects/index/controller-test.js

Enhancement: Project-Detailpage: MyStaffPilot
Re #459

Enhancement: Project-Detailpage: MyStaffPilot

---

app/styles/app.scss
app/styles/components/_content-quote.scss
app/styles/components/_project-technology.scss
app/styles/components/_project-text.scss
app/ui/components/project-technology/component.js
app/ui/components/project-technology/template.hbs
contents/de/projects/1.bmw.yaml
contents/de/projects/10.paulaner.yaml
contents/de/projects/2.knauf.yaml
contents/de/projects/3.idnow.yaml
contents/de/projects/5.mystaffpilot.yaml
contents/de/projects/6.tods.yaml
contents/de/projects/7.pingonaut.yaml
contents/de/projects/8.ferchau.yaml
contents/de/projects/9.audi.yaml
contents/en/projects/1.bmw.yaml
contents/en/projects/10.paulaner.yaml
contents/en/projects/2.knauf.yaml
contents/en/projects/3.idnow.yaml
contents/en/projects/5.mystaffpilot.yaml
contents/en/projects/6.tods.yaml
contents/en/projects/7.pingonaut.yaml
contents/en/projects/8.ferchau.yaml
contents/en/projects/9.audi.yaml
tests/integration/ui/components/project-technology/component-test.js

Project Detailpage: Smaller Design + Text Issues
Re #460

Project Detailpage: Smaller Design + Text Issues

---

app/styles/components/_page-menu.scss
app/ui/projects/detail/template.hbs
app/ui/projects/index/template.hbs

Navigation: Remove Back-Button, fix breadcrumbs on mobile
Re #461

Navigation: Remove Back-Button, fix breadcrumbs on mobile

---

app/styles/components/_content-quote.scss
app/styles/components/_project-technology.scss
app/styles/components/_project-text.scss
contents/de/projects/7.pingonaut.yaml
contents/en/projects/7.pingonaut.yaml

Small design issues

---

contents/de/projects/9.audi-disabled.yaml
contents/en/projects/9.audi-disabled.yaml

Rename Translationfiles. Change Project Title for overview Description
Re #471

Enhancement: Disable Audi Project Presentation for Release

---

app/styles/_config/_mixins/_customers.scss
app/styles/components/_content-lp-cover.scss
app/styles/components/_project-header.scss
app/styles/components/_project-technology.scss
app/styles/components/_projects-list.scss
app/ui/components/page-footer/component.js
app/ui/components/page-footer/template.hbs
app/ui/components/projects-list/component.js
app/ui/components/projects-list/template.hbs
contents/de/projects/11.bcg.yaml
contents/de/projects/12.knaufAroom.yaml
contents/de/projects/2.knaufLookbook.yaml
contents/en/projects/1.bmw.yaml
contents/en/projects/10.paulaner.yaml
contents/en/projects/11.bcg.yaml
contents/en/projects/12.knaufAroom.yaml
contents/en/projects/2.knaufLookbook.yaml
contents/en/projects/3.idnow.yaml
contents/en/projects/5.mystaffpilot.yaml
contents/en/projects/6.tods.yaml
contents/en/projects/7.pingonaut.yaml
contents/en/projects/8.ferchau.yaml
contents/en/projects/9.audi.yaml
translations/de.yaml
translations/en.yaml

Enhancement: Smaller design and text issues
Re #469

Enhancement: Smaller design and text issues

---

app/styles/components/_projects-list.scss

temporarily remove pointer events for disabled project tile
Re #476

Enhancement: Remove Hover Effect for disabled Project Tiles

---

contents/de/projects/12.knaufAroom.yaml
contents/en/projects/12.knaufAroom.yaml

Enhancement: fix typo in german translation of knauf project. add english translation for knauf project.
Re #478

Add Knauf Project Text

---

app/styles/components/_projects-list.scss
contents/de/projects/11.bcg-disabled.yaml
contents/en/projects/11.bcg-disabled.yaml

Disable BCG Project until Text is approved
Re #478

Enhancement: Temporarily disable BCG Project

---

app/styles/components/_project-header.scss

Bugfix: Set viewport relative value instead of auto value for container height
Re #481

Bugfix: Display issue with project-detail header background in firefox

---

config/ember-intl.js
tests/integration/ui/components/projects-list/component-test.js
translations/en.yaml

add missing translations to test Integration | Component | projects-list

---

.travis.yml
.travis/deploy-dev.sh
.travis/deploy-live.sh

update travis config and remove deploy-code

---

app/ui/components/page-footer/template.hbs
contents/de/imprint.yaml
contents/en/imprint.yaml

update privacy policy and imprint texts 

---

contents/de/projects/11.bcg-disabled.yaml
contents/de/projects/12.knaufAroom.yaml
contents/de/projects/2.knaufLookbook.yaml
contents/en/projects/11.bcg-disabled.yaml
contents/en/projects/12.knaufAroom.yaml
contents/en/projects/2.knaufLookbook.yaml

Enhancement: Change assets in overview
Re #492

Enhancement: Change assets in overview

---

app/styles/components/_projects-list.scss
contents/de/projects/9.audi.yaml
contents/en/projects/9.audi.yaml

Enable Audi Project for review

---

app/styles/components/_projects-list.scss

Enhancement: Update project overview
Re #494

Enhancement: Update project overview

---

contents/de/projects/3.idnow.yaml
contents/de/projects/6.tods.yaml
contents/en/projects/3.idnow.yaml
contents/en/projects/6.tods.yaml

Update Project-dates for IDNOW and TOD's

---

config/environment.js
package.json
yarn.lock

reset scroll-position on route-transition

---

app/router.js
app/ui/projects/detail/route.js

wrong (or shortended) project-title in browser-title bar used

---

app/router.js

remove unnecessary `path` option from router which matches the route name
